In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import statsmodels.api as sm

import seaborn as sns
sns.set()

In [2]:
raw_data = pd.read_csv("Social Media Dummy Data HSS.csv")
data = raw_data.copy()

In [3]:
data

,TV PROMOTION BUDGET in millions,Radio,Social Media,Influencer,Sales
0,16.0,6.566231,2.907983,Mega,54.732757
1,13.0,9.237765,2.409567,Mega,46.677897
2,41.0,15.886446,2.913410,Mega,150.177829
3,83.0,30.020028,6.922304,Mega,298.246340
4,15.0,8.437408,1.405998,Micro,56.594181
...,...,...,...,...,...
4567,26.0,4.472360,0.717090,Micro,94.685866
4568,71.0,20.610685,6.545573,Nano,249.101915
4569,44.0,19.800072,5.096192,Micro,163.631457
4570,71.0,17.534640,1.940873,Macro,253.610411
4571,42.0,15.966688,5.046548,Micro,148.202414

In [4]:
data.isnull().sum()

TV PROMOTION BUDGET in millions    10
Radio                               4
Social Media                        6
Influencer                          0
Sales                               6
dtype: int64

In [5]:
data = data.dropna()

In [6]:
data.isnull().sum()

TV PROMOTION BUDGET in millions    0
Radio                              0
Social Media                       0
Influencer                         0
Sales                              0
dtype: int64

In [7]:
data.describe()

       TV PROMOTION BUDGET in millions        Radio  Social Media        Sales
count                      4546.000000  4546.000000   4546.000000  4546.000000
mean                         54.062912    18.157533      3.323473   192.413332
std                          26.104942     9.663260      2.211254    93.019873
min                          10.000000     0.000684      0.000031    31.199409
25%                          32.000000    10.555355      1.530822   112.434612
50%                          53.000000    17.859513      3.055565   188.963678
75%                          77.000000    25.640603      4.804919   272.324236
max                         100.000000    48.871161     13.981662   364.079751

In [8]:
x1 = data[["TV PROMOTION BUDGET in millions","Radio","Social Media"]]
y = data["Sales"]

In [9]:
x = sm.add_constant(x1)
x.head()

   const  TV PROMOTION BUDGET in millions      Radio  Social Media
0    1.0                             16.0   6.566231      2.907983
1    1.0                             13.0   9.237765      2.409567
2    1.0                             41.0  15.886446      2.913410
3    1.0                             83.0  30.020028      6.922304
4    1.0                             15.0   8.437408      1.405998

In [10]:
model = sm.OLS(y,x).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.999
Model:                            OLS   Adj. R-squared:                  0.999
Method:                 Least Squares   F-statistic:                 1.505e+06
Date:                Wed, 05 Jun 2024   Prob (F-statistic):               0.00
Time:                        20:15:23   Log-Likelihood:                -11366.
No. Observations:                4546   AIC:                         2.274e+04
Df Residuals:                    4542   BIC:                         2.277e+04
Df Model:                           3
Covariance Type:            nonrobust
===================================================================================================
                                      coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
const                              -0.1340      0.103     -1.303      0.193      -0.336       0.068
TV PROMOTION BUDGET in millions     3.5626      0.003   1051.118      0.000       3.556       3.569
Radio                              -0.0040      0.010     -0.406      0.685      -0.023       0.015
Social Media                        0.0050      0.025      0.199      0.842      -0.044       0.054
==============================================================================
Omnibus:                        0.056   Durbin-Watson:                   1.998
Prob(Omnibus):                  0.972   Jarque-Bera (JB):                0.034
Skew:                          -0.001   Prob(JB):                        0.983
Kurtosis:                       3.013   Cond. No.                         149.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [11]:
y_cap = model.params[0]  + (model.params[1] * 16.0) + (model.params[2] * 6.566231) + (model.params[3] * 2.907983)
y_cap

C:\Users\dell\AppData\Local\Temp\ipykernel_3704\2298095230.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  y_cap = model.params[0]  + (model.params[1] * 16.0) + (model.params[2] * 6.566231) + (model.params[3] * 2.907983)

56.85551578590356

In [12]:
model.predict()

array([ 56.85551579,  46.15472574, 145.88277855, ..., 156.56578419,
       252.7484957 , 149.45561852])